### ISSUE TITLE
compiling with kernel-3.15.x fails

### ISSUE THREAD

**Issue by lowks** [akrasic/broadcom-wl#3]
Error happens when trying to compile with 3.15.x kernel

```
/home/lowks/src/broadcom-wl/src/wl/sys/wl_cfg80211_hybrid.c: In function ‘wl_notify_connect_status’:
/home/lowks/src/broadcom-wl/src/wl/sys/wl_cfg80211_hybrid.c:1844:4: warning: passing argument 3 of ‘cfg80211_ibss_joined’ makes pointer from integer without a cast [enabled by default]
    cfg80211_ibss_joined(ndev, (u8 *)&wl->bssid, GFP_KERNEL);
    ^
In file included from /home/lowks/src/broadcom-wl/src/wl/sys/wl_cfg80211_hybrid.c:33:0:
/usr/src/linux-3.15.0-33.g9194b64/include/net/cfg80211.h:3933:6: note: expected ‘struct ieee80211_channel *’ but argument is of type ‘unsigned int’
 void cfg80211_ibss_joined(struct net_device *dev, const u8 *bssid,
      ^
/home/lowks/src/broadcom-wl/src/wl/sys/wl_cfg80211_hybrid.c:1844:4: error: too few arguments to function ‘cfg80211_ibss_joined’
    cfg80211_ibss_joined(ndev, (u8 *)&wl->bssid, GFP_KERNEL);
    ^
In file included from /home/lowks/src/broadcom-wl/src/wl/sys/wl_cfg80211_hybrid.c:33:0:
/usr/src/linux-3.15.0-33.g9194b64/include/net/cfg80211.h:3933:6: note: declared here
 void cfg80211_ibss_joined(struct net_device *dev, const u8 *bssid,
```

**Comment by akrasic** [comment]
@lowks What's the distro/arch you're running ?

**Comment by lowks** [comment]
opensuse 13.1. my Kernel version:

```
lowks@lowkster:~/src/python> uname -r
3.15.0-33.g9194b64-desktop
```

I did a bit of leg work and what I found is this forum posting on gentoo which might be beneficial:

http://forums.gentoo.org/viewtopic-p-7568082.html

**Comment by akrasic** [comment]
I'll test the patches if they work..

**Comment by lowks** [comment]
do they work ?
